name: Prepare for Android
description: Prepares Android runtime (ie. installs java and sets everything up)
inputs:
  token:
    required: true
    description: "Your GitHub token"
  user:
    required: true
    description: "Your GitHub username"
  refName:
    required: false
    description: "Reference to set the version name to; usually github.ref_name. Must be specified together with refType"
  refType:
    required: false
    description: "Reference to infer the version name from; usually github.ref_type. Must be specified together with refName"
runs:
  using: composite
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        set -e
        # "git" required by "actions/checkout"
        # "unzip" required by "android-actions/setup-android"
        sudo apt update -y
        sudo apt install -y git unzip

    - name: Download repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: ${{ inputs.token }}

    - name: Enable cache
      uses: actions/cache@v4
      id: cache-android
      with:
        path: |
          ~/.gradle
          ~/.m2/repository
          ~/.android
        key: ${{ runner.os }}-android

    - name: Set VERSION_NAME variable (maven)
      shell: bash
      if: ${{ inputs.refName && inputs.refType }}
      run: |
        refName=${{ inputs.refName }}
        refType=${{ inputs.refType }}
        if [ $refType = "branch" ]; then
          refName="$refName-SNAPSHOT"
        fi
        echo "VERSION_NAME=$refName" >> gradle.properties

    - name: Set APP_VERSION_* variables (apk)
      shell: bash
      run: |
        versionName="${{ github.ref_name }}-${{ github.sha }}"
        versionCode=${{ github.run_number }}
        echo "APP_VERSION_NAME=$versionName" >> gradle.properties
        echo "APP_VERSION_CODE=$versionCode" >> gradle.properties

    - name: Set Github* variables (maven)
      shell: bash
      run: |
        echo "GithubPassword=${{ inputs.token }}" >> gradle.properties
        echo "GithubUsername=${{ inputs.user }}" >> gradle.properties

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Setup Android
      uses: android-actions/setup-android@v3
