name: Prepare for Android
description: Prepares Android runtime (ie. installs java and sets everything up)
inputs:
  keystore:
    required: false
    description: "Keystore Base64 encoded string"
  keystoreProperties:
    required: false
    description: "Keystore properties used for signing"
  versionCode:
    required: false
    description: "Version code to assign this build, if unassigned it uses `github.run_number`"
  versionName:
    required: false
    description: "Version name to assign this build, if unassigned it uses `github.ref_name`"
  setVariables:
    type: boolean
    default: true
    required: false
    description: "Sets variables required in order to build the projects"
runs:
  using: composite
  steps:
    - name: Enable cache
      uses: actions/cache@v4
      id: cache-android
      with:
        path: |
          ~/.android
        key: ${{ runner.os }}-android

    - name: Set APP_VERSION_* variables (apk)
      if: ${{ inputs.setVariables }}
      shell: bash
      run: |
        sha=${{ github.sha }}
        sha=${sha:0:7}
        versionName=${{ inputs.versionName }}
        versionCode=${{ inputs.versionCode }}
        if [ -z "$versionCode" ]; then
          versionCode=${{ github.run_number }}
        fi
        if [ -z "$versionName" ]; then
          versionName=${{ github.ref_name }}
          if [ "${{ github.ref_type }}" == "branch" ]; then
            versionName="$versionName-SNAPSHOT"
          fi
        fi
        echo "APP_VERSION_NAME=$versionName" >> gradle.properties
        echo "APP_VERSION_CODE=$versionCode" >> gradle.properties
        echo "APP_VERSION_HASH=$sha" >> gradle.properties

    - name: Unwrap platform.* for signing
      shell: bash
      if: ${{ inputs.keystore && inputs.keystoreProperties }}
      run: |
        keystore=${{ inputs.keystore }}
        keystoreProperties=${{ inputs.keystoreProperties }}
        
        echo $keystore | base64 --decode > platform.keystore
        echo $keystoreProperties | base64 --decode > platform.properties

    - name: Setup Android
      uses: android-actions/setup-android@v3
