name: Prepare for Android
description: Prepares Android runtime (ie. installs java and sets everything up)
inputs:
  keystore:
    required: false
    description: "Keystore Base64 encoded string"
  keystoreProperties:
    required: false
    description: "Keystore properties used for signing"
runs:
  using: composite
  steps:
    - name: Enable cache
      uses: actions/cache@v4
      id: cache-android
      with:
        path: |
          ~/.android
        key: ${{ runner.os }}-android

    - name: Set APP_VERSION_* variables (apk)
      shell: bash
      run: |
        sha=${{ github.sha }}
        sha=${sha:0:7}
        versionName="${{ github.ref_name }}-$sha"
        versionCode=${{ github.run_number }}
        echo "APP_VERSION_NAME=$versionName" >> gradle.properties
        echo "APP_VERSION_CODE=$versionCode" >> gradle.properties

    - name: Unwrap platform.* for signing
      shell: bash
      if: ${{ inputs.keystore && inputs.keystoreProperties }}
      run: |
        keystore=${{ inputs.keystore }}
        keystoreProperties=${{ inputs.keystoreProperties }}
        
        echo $keystore | base64 --decode > platform.keystore
        echo $keystoreProperties | base64 --decode > platform.properties

    - name: Setup Android
      uses: android-actions/setup-android@v3
