name: Prepare for JVM
description: Prepares JVM runtime
inputs:
  mavenPassword:
    required: false
    description: "Your Maven token"
  mavenUsername:
    required: false
    description: "Your Maven username"
  javaVersion:
    required: false
    default: "17"
    description: "Java level"
  versionName:
    required: false
    description: "Version name to use instead of `github.ref_name`"
  setVariables:
    required: false
    default: "yes"
    description: "Sets variables required in order to build the projects"

runs:
  using: composite
  steps:
    - name: Enable cache
      uses: actions/cache@v4
      id: cache-jvm
      with:
        path: |
          ~/.gradle
          ~/.m2/repository
        key: ${{ runner.os }}-jvm

    - name: Set Maven* variables
      shell: bash
      if: ${{ inputs.mavenPassword && inputs.mavenUsername }}
      run: |
        echo "MavenPassword=${{ inputs.mavenPassword }}" >> gradle.properties
        echo "MavenUsername=${{ inputs.mavenUsername }}" >> gradle.properties

    - name: Set VERSION_NAME variable (maven)
      shell: bash
      if: ${{ inputs.setVariables }}
      run: |
        versionName=${{ inputs.versionName }}
        if [ -z "$versionName" ]; then
          if [ "${{ github.ref_type }}" == "branch" ]; then
            versionName="$(jq -c -r -M ".." .release-please-manifest.json | tail -1)-SNAPSHOT"
          else
            echo "versionName not set type=${{github.ref_type}}, using github.ref_name=${{github.ref_name}}"
            versionName=${{ github.ref_name }}
          fi
        fi
        echo "VERSION_NAME=$versionName" >> gradle.properties

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.javaVersion }}
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
