name: Build and Publish

on:
  workflow_call:
    inputs:
      refName:
        required: true
        type: string
      refType:
        required: true
        type: string
    secrets:
      AUTH_TOKEN:
        required: true
      AUTH_USER:
        required: true

jobs:
  publish-aar:
    runs-on: prague-runners
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.AUTH_TOKEN }}

      - run: |
          refName=${{ inputs.refName }}
          refType=${{ inputs.refType }}
          if [ $refType = "branch" ]; then
            refName="$refName-SNAPSHOT"
          fi
          echo "VERSION_NAME=$refName" >> gradle.properties
          echo "GithubPassword=${{ secrets.AUTH_TOKEN }}" >> gradle.properties
          echo "GithubUsername=${{ secrets.AUTH_USER }}" >> gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: publishAllPublicationsToGithubRepository --continue
