name: Checks

on:
  workflow_call:
    inputs:
      checkCompatibility:
        required: false
        type: boolean
        default: true
      android:
        required: false
        type: boolean
        default: true
    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  test:
    runs-on: prague-runners
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
      - uses: ozobot/anvil-ci/.github/actions/android@master
        if: ${{ inputs.android }}

      - shell: bash
        run: ./gradlew test --no-daemon

      - uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Tests
          path: "**/test-results/**/*.xml"
          reporter: java-junit
          fail-on-empty: false

  compatibility:
    runs-on: prague-runners
    if: ${{ inputs.checkCompatibility }}
    permissions:
      contents: read
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
      - uses: ozobot/anvil-ci/.github/actions/android@master
        if: ${{ inputs.android }}

      - shell: bash
        run: ./gradlew apiCheck --no-daemon

  lint:
    if: ${{ inputs.android }}
    runs-on: prague-runners
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
      - uses: ozobot/anvil-ci/.github/actions/android@master

      - shell: bash
        run: ./gradlew lint --no-daemon

  merge:
    needs: [ test, compatibility, lint ]
    uses: ozobot/anvil-ci/.github/workflows/dependabot-merge.yml@master
    secrets: inherit
