name: Checks

on:
  workflow_call:
    inputs:
      android:
        required: false
        type: boolean
        default: true

jobs:
  dependency-submission:
    runs-on: prague-runners
    steps:
      - uses: ozobot/android-ci/.github/actions/checkout@master
      - uses: ozobot/android-ci/.github/actions/jvm@master
      - uses: ozobot/android-ci/.github/actions/android@master
        if: ${{ inputs.android }}

      - uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph-exclude-projects: ':buildSrc'
          dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
          dependency-resolution-task: assemble