name: Checks

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      maintainer:
        required: false
        type: string
        default: "diareuse"
    secrets:
      AUTH_TOKEN:
        required: true
      AUTH_USER:
        required: true

jobs:
  test:
    runs-on: prague-runners-dind
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: ./.github/actions/android
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          user: ${{ secrets.AUTH_USER }}

      - uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: test

      - uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        if: always()
        with:
          junit_files: "**/test-results/**/*.xml"

  lint:
    runs-on: prague-runners
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: ./.github/actions/android
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          user: ${{ secrets.AUTH_USER }}

      - uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: detekt

      - uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        if: always()
        with:
          path: '**/merge.xml'

  merge:
    needs: [ test, lint ]
    uses: ./.github/workflows/dependabot-merge.yml
    secrets: inherit

  assign:
    uses: ./.github/workflows/dependabot-assign.yml
    with:
      maintainer: ${{ inputs.maintainer }}
    secrets: inherit