name: Build and Publish

on:
  workflow_call:
    secrets:
      MAVEN_PASSWORD:
        required: true
      MAVEN_USERNAME:
        required: true

jobs:
  publish-artifacts:
    runs-on: prague-runners
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
        with:
          mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
          mavenUsername: ${{ secrets.MAVEN_USERNAME }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew publish --continue
