name: Publish artifacts for base OS

on:
  workflow_call:
    secrets:
      MAVEN_PASSWORD:
        required: true
      MAVEN_USERNAME:
        required: true
      KEYSTORE_FILE:
        required: true
      KEYSTORE_PROPERTIES:
        required: true

jobs:
  publish-artifacts:
    runs-on: prague-runners
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
        with:
          mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
          mavenUsername: ${{ secrets.MAVEN_USERNAME }}
          versionName: os-SNAPSHOT
      - uses: ozobot/anvil-ci/.github/actions/android@master
        with:
          keystore: ${{ secrets.KEYSTORE_FILE }}
          keystoreProperties: ${{ secrets.KEYSTORE_PROPERTIES }}
          versionCode: 1
          versionName: 33

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew publish --continue

      - name: Upload to Github
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          compression-level: 0
          retention-days: 1
          overwrite: true
          if-no-files-found: error
          path: |
            **/build/outputs/apk/**/*.apk
