name: Build and Publish

on:
  workflow_call:
    secrets:
      MAVEN_PASSWORD:
        required: true
      MAVEN_USERNAME:
        required: true
      KEYSTORE_FILE:
        required: true
      KEYSTORE_PROPERTIES:
        required: true
    inputs:
      app:
        required: false
        type: boolean
        default: true

jobs:
  publish-artifacts:
    runs-on: prague-runners
    steps:
      - uses: ozobot/android-ci/.github/actions/checkout@master
      - uses: ozobot/android-ci/.github/actions/jvm@master
        with:
          mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
          mavenUsername: ${{ secrets.MAVEN_USERNAME }}
      - uses: ozobot/android-ci/.github/actions/android@master
        with:
          keystore: ${{ secrets.KEYSTORE_FILE }}
          keystoreProperties: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: Generate next version code
        if: ${{ inputs.app }}
        run: ./gradlew generateVersionCode --no-daemon --stacktrace

      - name: Build with Gradle
        if: always()
        run: ./gradlew publish --continue --no-daemon
