name: Build and Publish

on:
  workflow_call:
    secrets:
      MAVEN_PASSWORD:
        required: true
      MAVEN_USERNAME:
        required: true
      KEYSTORE_FILE:
        required: true
      KEYSTORE_PROPERTIES:
        required: true

jobs:
  publish-artifacts:
    runs-on: prague-runners
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/jvm@master
        with:
          mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
          mavenUsername: ${{ secrets.MAVEN_USERNAME }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish --continue
