name: Update translations

on:
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true
    inputs:
      filePath:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  translate-resources:
    runs-on: prague-runners-dind
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/translate@master
        with:
          filePath: ${{ inputs.filePath }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            *.xml
          commit-message: "feat: update translations"
          labels: i18n
          title: update translations
          body: Translations have been updated by running it through Gemini LLM.
          base: master
          branch: update/translations
