name: Update translations

on:
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true
    inputs:
      filePath:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  translate-resources:
    runs-on: prague-runners-dind
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - uses: ozobot/anvil-ci/.github/actions/translate@master
        with:
          filePath: ${{ inputs.filePath }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
      - run: |
          git config user.name 'Gemini[bot]'
          git config user.email 'gemini@users.noreply.github.com'
          git add -- *.xml
          git commit -m "chore(strings): update translations"
          git push -f origin chore/update-translations
      - uses: ozobot/anvil-ci/.github/actions/github-cli@master
      - name: Create pull request
        run: gh pr create --title "Update translations" --body "Update translations" --base master --head chore/update-translations
        env:
          GH_TOKEN: ${{secrets.AUTH_TOKEN}}
