name: Update translations

on:
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true
    inputs:
      filePath:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  translate-resources:
    runs-on: prague-runners-dind
    steps:
      - uses: ozobot/anvil-ci/.github/actions/checkout@master
      - run: |
          git config user.name 'Gemini[bot]'
          git config user.email 'gemini@users.noreply.github.com'
          git fetch origin master
          git checkout -b chore/update-translations
      - uses: ozobot/anvil-ci/.github/actions/translate@master
        with:
          filePath: ${{ inputs.filePath }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
      - name: Create commit
        run: |
          git add -- *.xml
          git commit -m "chore(strings): update translations"
      - name: Pull changes from remote
        continue-on-error: true
        run: |
          git pull -r --ff-only origin chore/update-translations > /dev/null 2>&1
      - name: Push to remote
        run: |
          git push origin chore/update-translations
      - uses: ozobot/anvil-ci/.github/actions/github-cli@master
      - name: Create pull request
        run: |
          pull_request_count=$(gh pr list -H chore/update-translations | wc -l)
          if [ $pull_request_count -eq 0 ]; then
            gh pr create --title "Update translations" --body "Updated translations as translated from Gemini LLM." --base master --head chore/update-translations
          fi
        env:
          GH_TOKEN: ${{secrets.AUTH_TOKEN}}
